# See https://github.com/actions/starter-workflows/blob/1dd15d20337289b85cecafdde824b3a44bc8ed27/ci/ruby.yml
# which was used as a reference
name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.4']
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install gem deps
        run: bundle install
      - name: Run tests
        run: |
          sudo apt update
          sudo apt install expect gdb valgrind
          VALGRIND=1 bundle exec ./ruby34_bug_wrapper.sh
